### ISSUE TITLE
Buffer sizes are incorrect for CV1

### ISSUE THREAD

**Issue by num3ric** [num3ric/Cinder-OculusRift#11]

**Comment by ulyssesdotcodes** [comment]
My CV1 seems to be rendering with a weird offset in each eye. Is this what could be causing it?

**Comment by num3ric** [comment]
Actually, it could be because the CV1 has asymmetric lenses, as described in the comments here:
https://forums.oculus.com/developer/discussion/36823/single-buffer-for-two-eyes-still-supported#latest

Sounds probable that the issue is with the projection matrix. Will debug it further in the coming days...

**Comment by num3ric** [comment]
Fixed in 0e9fe765202edfa48c74f1622579cec7f5cc155c

The issue was indeed related to an incorrectly cached projection matrix.
