### ISSUE TITLE
osx can't get above 60fps with vertical sync

### ISSUE THREAD

**Issue by m1keall1son** [num3ric/Cinder-OculusRift#4]
I'm on osx 10.9.5 and can't get above 60fps regardless of disabling framerate or setting it to 75 while vertical sync is on.  If i turn vertical sync off i can get higher rates but there's tearing occasionally and its all over the place.

I think that vertical sync is causing it to sync to the main display instead of the rift display.  I'm not sure i know a fix off hand.

**Comment by num3ric** [comment]
Closing. OS X is no longer supported by Oculus.
