### ISSUE TITLE
Cannot change near/far clip

### ISSUE THREAD

**Issue by grrrwaaa** [num3ric/Cinder-OculusRift#6]
There is no way to set the near/far clip for rendering. Setting a higher near clip can be useful to avoid stuff poking in the eye, and reducing the far clip can improve depth resolution for smaller scenes. 

mEyeCamera seems to be the way to modify it, but this is only accessible as a const reference.

**Comment by num3ric** [comment]
@grrrwaaa True. On it!

Edit: Would an additional Params option suffice?
